---

spring: 
    profile: dev

    jpa:
        
        hibernate:
            ddl-auto: update
    datasource:
        platform: mysql
        url: jdbc:mysql://localhost:3306/APR?ssl=false
        username: root
        password: root
        driverClassName: com.mysql.jdbc.Driver
  
---
